### PR TITLE
allow BUNDLE_IDENTIFIER to be set in package-info.json.in

### PR DESCRIPTION
**Pull request by tschiemer**
Hi! Many thanks for the library.

When not using xcode and its build environment - that is, directly calling `cmake . ` and `make` - the plists BUNDLE_IDENTIFIER is set to `${PRODUCT_NAME:rfc1034identifier}` which is also how it will end up in the created external.

I think it would be meaningful to allow it to be set using the `package-info.json.in` file as is done with several similiar fields.

This way it can be set in any cmake file or in the package-info file - and if it is not set, it will stay the same as before - to be set by xcode.

### CODE REVIEW

**Comment by tschiemer** [comment]
second commit:

When using a project structure differing from the setup given in the [max-sdk](https://github.com/Cycling74/max-sdk) the external/extension output paths might lie where it definitely should not as it is *always* assumed to be three folders below the assumed base directory.
ie fewer (or more) subdirectories mess things up.

https://github.com/Cycling74/max-api/blob/db2773956d8b9a338a529f30d4953e0bbf162c13/script/max-pretarget.cmake#L38

**Comment by tap** [comment]
Hi! Thanks for the pull request! I'm reviewing now.

Before we can merge anything I'll need to ask you to fill out a CLA at https://cycling74.com/cla -- this just needs to be done once and then we can accept pull requests from you. Thanks!

**Comment by tap** [comment]
Thanks for filing the CLA @tschiemer !

We've reviewed this now and have a few comments.

First, we are requiring that Xcode be used as the compiler. As a result, we are not planning on changing the BUNDLE_IDENTIFIER as this is already a variable that is substituted by Xcode with the appropriate result. 

This isn't to say that you can't substitute it differently in your own CMake scripts. If you wish do so, then by all means do!

Second, the other commit (which probably should be a separate pull request), is a very valid concern. The paths in our current CMake arrangement are making assumptions that are brittle, and I appreciate you raising awareness about that. Simply applying the proposed change, however, is going to break a lot of things without first modifying the surrounding tooling. 

So that can't be accepted as is, but it is a valid criticism and we should work to make that better. If you would like to separate that out into its own issue and/or pull request we can work on it further in that context.

Thanks for taking the time!

**Comment by tschiemer** [comment]
Hi!

Thanks for the comments

My suggestion regarding the BUNDLE_IDENTIFIER would have been to *allow* substituting it using the package description file but keeping it default as is (also not to break any existing setup), to be conclusively substituted by xcode. Thus making it out-of-the box simpler to override this setting without the need of patching the existing build system (or substituting parts of it).

Naturally you may choose to require xcode as IDE ;) but you exclude developers preferring just using the [command line tools](https://developer.apple.com/library/archive/technotes/tn2339/_index.html#targetText=The%20Command%20Line%20Tools%20Package%20is%20a%20small%20self%2Dcontained,Library%2FDeveloper%2FCommandLineTools%20directory.) doing the grunt work..

Regarding the path arrangement (yes, I should have made a separate pull request, sorry for that), I'll put that into a pull request of its own any of these days, as you suggest.

Have a nice day!

**Pull request closed without merging**
